# Site settings
name: Nicole Teo
email: nico.thyun@gmail.com
url: "http://nicothyun.github.io" # the base hostname & protocol for your site
description: Hi I am Nicole and I'm a marketer.
title: "Nicole Teo, Marketing & Strategy"

plugins:
  - octopress-autoprefixer

tags:
  - jekyll
  - code

# Social
twitter: 0xniccomi
github: nicothyun

# Build settings
markdown: kramdown


# Serving
port: 4000
host: 0.0.0.0

permalink: pretty

sass:
    style: :compressed

exclude: [vendor]
